name: Coverage Reporting

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
        pip install -e .
    
    - name: Run tests with detailed coverage
      run: |
        pytest --cov=src/crossmark_jotform_api --cov-report=term-missing --cov-report=html --cov-report=xml --cov-branch -v tests/
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: coverage.xml
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload coverage to Codecov (alternative)
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Archive coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: htmlcov/